archive = "bionic"
version = "18.04"
origin = "system76"
label = "System76"
email = "info@system76.com"
extra_repos = [ "deb http://ppa.launchpad.net/system76/pop/ubuntu bionic main" ]

[[direct]]
name = "code"
version = "1.35.1-1560350270"

    [[direct.urls]]
    url = "https://az764295.vo.msecnd.net/stable/c7d83e57cd18f18026a8162d042843bda1bcf21f/code_1.35.1-1560350270_amd64.deb"
    checksum = "c3bb7a6d7953ff4093b8a7229227ad4a9587900866c7e867710086dcd42ba482"

[[direct]]
name = "discord"
version = "0.0.9"

    [[direct.urls]]
    url = "https://dl.discordapp.net/apps/linux/0.0.9/discord-0.0.9.deb"
    checksum = "2a5f0f0e940d2d2dbb9a789baab1a58a54e7dacc598d628b2667b5244df84bbf"
    arch = "amd64"

[[direct]]
name = "slack-desktop"
version = "3.4.0"

    [[direct.urls]]
    url = "https://downloads.slack-edge.com/linux_releases/${name}-${version}-amd64.deb"
    checksum = "857b38862aa732a27c1cee5fcfdce490d624f22a5d8b4fd389d7ad06de1ba551"

[[direct]]
name = "spotify-client"
version = "1.1.5.153.gf614956d-16"

    [[direct.urls]]
    url = "http://repository.spotify.com/pool/non-free/s/${name}/${name}_${version}_amd64.deb"
    checksum = "a7e189c430af1788c4f7d02ae411bfb38f0eccc5f829218d9dc81e1dab382037"

[[direct]]
name = "signal-desktop"
version = "1.25.1"

    [[direct.urls]]
    url = "https://updates.signal.org/desktop/apt/pool/main/s/${name}/${name}_${version}_amd64.deb"
    checksum = "97863be20e80d72537d5ea169202eb4c123f285ca8be7c3490b8aa91b6be0585"

[[direct]]
name = "google-chrome-stable"
version = "current"

    [[direct.urls]]
    url = "https://dl.google.com/linux/direct/${name}_${version}_amd64.deb"

[[direct]]
name = "gitkraken"
version = "current"

    [[direct.urls]]
    url = "https://release.gitkraken.com/linux/${name}-amd64.deb"
