archive = "cosmic"
version = "18.04"
origin = "system76"
label = "System76"
email = "info@system76.com"
architectures = [ "amd64" ]
extra_repos = [ "deb http://ppa.launchpad.net/system76/pop/ubuntu cosmic main" ]

[[direct]]
name = "code"
version = "1.36.1-1562627527"

    [[direct.urls]]
    url = "https://az764295.vo.msecnd.net/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/code_1.36.1-1562627527_amd64.deb"
    checksum = "397777c2f86826029551395ff93a26781d51b86dd16b5741ae285f283422fd4e"

[[direct]]
name = "discord"
version = "0.0.9"

    [[direct.urls]]
    url = "https://dl.discordapp.net/apps/linux/0.0.9/discord-0.0.9.deb"
    checksum = "2a5f0f0e940d2d2dbb9a789baab1a58a54e7dacc598d628b2667b5244df84bbf"
    arch = "amd64"

[[direct]]
name = "slack-desktop"
version = "3.4.2"

    [[direct.urls]]
    url = "https://downloads.slack-edge.com/linux_releases/${name}-${version}-amd64.deb"
    checksum = "3833c1abdbd15b50d9f3e4f77deb4bf6d578cfebfeab2b6ee0e84f567d207261"

[[direct]]
name = "spotify-client"
version = "1.1.10.546.ge08ef575-19"

    [[direct.urls]]
    url = "http://repository.spotify.com/pool/non-free/s/${name}/${name}_${version}_amd64.deb"
    checksum = "da49fd4d222ff7d719345fba6298f38a6422ef293bb43ada13cf857a694a12e6"

[[direct]]
name = "signal-desktop"
version = "1.25.3"

    [[direct.urls]]
    url = "https://updates.signal.org/desktop/apt/pool/main/s/${name}/${name}_${version}_amd64.deb"
    checksum = "2319a0171198890bbf30c8e7ba777cc564904189b71f631cefb19fd4c88df738"

[[direct]]
name = "google-chrome-stable"
version = "current"

    [[direct.urls]]
    url = "https://dl.google.com/linux/direct/${name}_${version}_amd64.deb"

[[direct]]
name = "gitkraken"
version = "current"

    [[direct.urls]]
    url = "https://release.gitkraken.com/linux/${name}-amd64.deb"
