archive = "cosmic"
version = "18.04"
origin = "system76"
label = "System76"
email = "info@system76.com"
extra_repos = [ "deb http://ppa.launchpad.net/system76/pop/ubuntu cosmic main" ]

[[direct]]
name = "code"
version = "1.34.0-1557957934"

    [[direct.urls]]
    url = "https://az764295.vo.msecnd.net/stable/a622c65b2c713c890fcf4fbf07cf34049d5fe758/code_1.34.0-1557957934_amd64.deb"
    checksum = "b4c198ae6c9a4908a8f6c3fd4375eb3d876057bf95089181c09b35fb6b28de6c"

[[direct]]
name = "discord"
version = "0.0.9"

    [[direct.urls]]
    url = "https://dl.discordapp.net/apps/linux/0.0.9/discord-0.0.9.deb"
    checksum = "2a5f0f0e940d2d2dbb9a789baab1a58a54e7dacc598d628b2667b5244df84bbf"
    arch = "amd64"

[[direct]]
name = "slack-desktop"
version = "3.4.2"

    [[direct.urls]]
    url = "https://downloads.slack-edge.com/linux_releases/${name}-${version}-amd64.deb"
    checksum = "3833c1abdbd15b50d9f3e4f77deb4bf6d578cfebfeab2b6ee0e84f567d207261"

[[direct]]
name = "spotify-client"
version = "1.1.0.237.g378f6f25-11"

    [[direct.urls]]
    url = "http://repository.spotify.com/pool/non-free/s/${name}/${name}_${version}_amd64.deb"
    checksum = "4b77c6baa59d5e8d8e6f800138fefdf579747cb81615b9711dfa25d6c2d5fa9f"

[[direct]]
name = "signal-desktop"
version = "1.23.1"

    [[direct.urls]]
    url = "https://updates.signal.org/desktop/apt/pool/main/s/${name}/${name}_${version}_amd64.deb"
    checksum = "9ad4f2eea627f6640fa72141f1a849077b73fceccdfb2e2a629cc163da051ac4"

[[direct]]
name = "google-chrome-stable"
version = "current"

    [[direct.urls]]
    url = "https://dl.google.com/linux/direct/${name}_${version}_amd64.deb"

[[direct]]
name = "gitkraken"
version = "current"

    [[direct.urls]]
    url = "https://release.gitkraken.com/linux/${name}-amd64.deb"
