archive = "disco"
version = "19.04"
origin = "system76"
label = "System76"
email = "info@system76.com"
architectures = [ "amd64" ]
extra_repos = [ "deb http://ppa.launchpad.net/system76/pop/ubuntu disco main" ]

[[direct]]
name = "code"
version = "1.39.1-1570750687"

    [[direct.urls]]
    url = "https://az764295.vo.msecnd.net/stable/88f15d17dca836346e787762685a40bb5cce75a8/code_1.39.1-1570750687_amd64.deb"
    checksum = "bf5a0f1600a6cd26753606de40c12ba598861c4142d77eeab97209ad546631b5"

[[direct]]
name = "discord"
version = "0.0.9"

    [[direct.urls]]
    url = "https://dl.discordapp.net/apps/linux/0.0.9/discord-0.0.9.deb"
    checksum = "2a5f0f0e940d2d2dbb9a789baab1a58a54e7dacc598d628b2667b5244df84bbf"
    arch = "amd64"

[[direct]]
name = "slack-desktop"
version = "4.1.1"

    [[direct.urls]]
    url = "https://downloads.slack-edge.com/linux_releases/${name}-${version}-amd64.deb"
    checksum = "2e84af28a9179faf1a6c64e36e6316792531de1d4530fcd2909e5eae77d1ced9"

[[direct]]
name = "spotify-client"
version = "1.1.10.546.ge08ef575-19"

    [[direct.urls]]
    url = "http://repository.spotify.com/pool/non-free/s/${name}/${name}_${version}_amd64.deb"
    checksum = "da49fd4d222ff7d719345fba6298f38a6422ef293bb43ada13cf857a694a12e6"

[[direct]]
name = "signal-desktop"
version = "1.27.4"

    [[direct.urls]]
    url = "https://updates.signal.org/desktop/apt/pool/main/s/signal-desktop/signal-desktop_1.27.4_amd64.deb"
    checksum = "5297d7efe843c61ee5e874009a076ec5b6f74974b79675f6c4a9ff0e8e0eeaab"

[[direct]]
name = "google-chrome-stable"
version = "current"

    [[direct.urls]]
    url = "https://dl.google.com/linux/direct/${name}_${version}_amd64.deb"

[[direct]]
name = "gitkraken"
version = "current"

    [[direct.urls]]
    url = "https://release.gitkraken.com/linux/${name}-amd64.deb"
