archive = "eoan"
version = "19.10"
origin = "system76"
label = "System76"
email = "info@system76.com"
architectures = [ "amd64" ]
extra_repos = [ "deb http://ppa.launchpad.net/system76/pop/ubuntu eoan main" ]

[[direct]]
name = "code"
version = "1.41.0-1576089540"

    [[direct.urls]]
    url = "https://az764295.vo.msecnd.net/stable/9579eda04fdb3a9bba2750f15193e5fafe16b959/code_1.41.0-1576089540_amd64.deb"
    checksum = "1a31d11fa22432905a0bdfc097559ebaaff60730716b67b626080fff6f27848a"

[[direct]]
name = "discord"
version = "0.0.9"

    [[direct.urls]]
    url = "https://dl.discordapp.net/apps/linux/0.0.9/discord-0.0.9.deb"
    checksum = "2a5f0f0e940d2d2dbb9a789baab1a58a54e7dacc598d628b2667b5244df84bbf"
    arch = "amd64"

[[direct]]
name = "slack-desktop"
version = "4.2.0"

    [[direct.urls]]
    url = "https://downloads.slack-edge.com/linux_releases/${name}-${version}-amd64.deb"
    checksum = "db4666023c1b82f0f7fbfbdbeb04b485898edb73ca5d869b8c8e003f219d6205"

[[direct]]
name = "spotify-client"
version = "1.1.10.546.ge08ef575-19"

    [[direct.urls]]
    url = "http://repository.spotify.com/pool/non-free/s/${name}/${name}_${version}_amd64.deb"
    checksum = "da49fd4d222ff7d719345fba6298f38a6422ef293bb43ada13cf857a694a12e6"

[[direct]]
name = "signal-desktop"
version = "1.29.0"

    [[direct.urls]]
    url = "https://updates.signal.org/desktop/apt/pool/main/s/signal-desktop/signal-desktop_1.29.0_amd64.deb"
    checksum = "163bc8edc3bc402b63b40aa4560004b1cd902f3fc6ae7292fbe655b8c80772fd"

[[direct]]
name = "google-chrome-stable"
version = "current"

    [[direct.urls]]
    url = "https://dl.google.com/linux/direct/${name}_${version}_amd64.deb"

[[direct]]
name = "gitkraken"
version = "current"

    [[direct.urls]]
    url = "https://release.gitkraken.com/linux/${name}-amd64.deb"

[[direct]]
name = "plex-media-server"
version = "1.18.2.2058-e67a4e892"

    [[direct.urls]]
    url = "https://downloads.plex.tv/plex-media-server-new/1.18.2.2058-e67a4e892/debian/plexmediaserver_1.18.2.2058-e67a4e892_amd64.deb"
    checksum = "a48082bce73747257ca754198992214ff3fad805fe989ff2fda46052315f38b1"
